#!/bin/bash

source ./environment.sh

$TERMINAL PeriodicTimer.frequency 50

$TERMINAL Dev.posGain 0.00002262443

$TERMINAL Dev.angleGain 0.0003870809
$TERMINAL Dev.angleOffset -1.2328527249

$TERMINAL Dev.gyroGain 1.5259e-5
$TERMINAL Dev.gyroOffset 0.0

$TERMINAL Motor.ki 0.033
$TERMINAL Motor.kv 0.033
$TERMINAL Motor.rm 4.72

$TERMINAL Dev.oversampling 100
$TERMINAL SPI.enabled 1

$TERMINAL cfgFilter ang 50 0.7
$TERMINAL cfgFilter pos 50 0.7
$TERMINAL cfgFilter gyro 50 0.7
$TERMINAL cfgFilter gyro_hpf 1 0.7

$TERMINAL Traces.streaming 1

$TERMINAL dumpParameters
