#!/bin/bash

source ./environment.sh

$TERMINAL Controller.minAng -7.5
$TERMINAL Controller.maxAng 7.5

$TERMINAL Controller.pos_sp 0.0
$TERMINAL Controller.pos_kp 0
$TERMINAL Controller.pos_kd 0
$TERMINAL Controller.pos_ki 0.0

$TERMINAL Controller.ang_sp 0.0
$TERMINAL Controller.ang_kp -50 
$TERMINAL Controller.ang_kd -5
$TERMINAL Controller.ang_ki 0.0

$TERMINAL Controller.inj_freq 2.5
$TERMINAL Controller.inj_ampl 0.0

$TERMINAL SPI.enabled 1
$TERMINAL dumpParameters