#!/bin/bash

source ./environment.sh

# Note: offset is added after multiplication with gain
#       Changing gain must be followed by changing offset.


$TERMINAL CmdUpdateFrequency.frequency 100

$TERMINAL Dev.Encoder.nrIncrements 4096

$TERMINAL Dev.acc.go.gain    0.0033674684
$TERMINAL Dev.acc.go.offset -123.4

$TERMINAL Dev.gyro_Dev.gyroref.diff.go.gain   -0.012
$TERMINAL Dev.gyro_Dev.gyroref.diff.go.offset -7.0

$TERMINAL Dev.Encoder.go.gain 0.00002262443

$TERMINAL cfgFilter Dev.gyro_Dev.gyroref.diff.go.hpf.filter 0.1 0.7

$TERMINAL addTrace Dev.DutyCycle.value
$TERMINAL addTrace Controller.alfa
$TERMINAL addTrace Controller.alfa_dot
$TERMINAL addTrace Controller.x
$TERMINAL addTrace Controller.x_dot


$TERMINAL SPI.enabled 1


exit 0




$TERMINAL Motor.ki 0.033
$TERMINAL Motor.kv 0.033
$TERMINAL Motor.rm 4.72

$TERMINAL Dev.oversampling 11
$TERMINAL SPI.oversampling 11

$TERMINAL cfgFilter ang 60 0.7
$TERMINAL cfgFilter acc 6 0.7
$TERMINAL cfgFilter pos 60 0.7
$TERMINAL cfgFilter gyro 60 0.7
$TERMINAL cfgFilter gyro_hpf 0.1 0.7

$TERMINAL Traces.streaming 1


$TERMINAL dumpParameters

